// sgl_hancode_table.h

#ifndef __SGL_HANCODE_TABLE_H
#define __SGL_HANCODE_TABLE_H

#define SGL_HANCODE_SINGLE_TABLE_SIZE		51
#define SGL_HANCODE_TABLE_SIZE				2350

extern UInt16 SGL_HANCODE_SINGLE_TABLE[SGL_HANCODE_SINGLE_TABLE_SIZE];
extern UInt16 SGL_HANCODE_TABLE[SGL_HANCODE_TABLE_SIZE];

#endif // __SGL_HANCODE_TABLE_H
