// sgl_unicode_table.h

#ifndef _SGL_UNICODE_TABLE_H
#define _SGL_UNICODE_TABLE_H

#define SGL_UCS2_TO_KSSM_CHO_TABLE_SIZE			19
#define SGL_UCS2_TO_KSSM_JUNG_TABLE_SIZE		21
#define SGL_KSC5601_TO_UCS2_TABLE_SIZE			8742

extern UInt16	 SGL_UCS2_TO_KSSM_CHO_TABLE[SGL_UCS2_TO_KSSM_CHO_TABLE_SIZE];
extern UInt16	SGL_UCS2_TO_KSSM_JUNG_TABLE[SGL_UCS2_TO_KSSM_JUNG_TABLE_SIZE];
extern UInt16	SGL_KSC5601_TO_UCS2_TABLE[SGL_KSC5601_TO_UCS2_TABLE_SIZE];

#endif
